# Generated by Django 5.2.5 on 2025-08-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_category_document_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
